name: ridy
description: Driver application of Ridy

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.3.5+117

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  artemis: 7.7.0-beta
  country_code_picker: ^2.0.2
  country_codes: ^2.2.0
  dotted_line: ^3.1.0
  equatable: ^2.0.5
  file_picker: ^5.2.0+1
  firebase_analytics: 10.0.4
  firebase_auth: 4.1.1
  firebase_core: 2.1.1
  firebase_crashlytics: 3.0.4
  firebase_messaging: 14.0.4
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_chat_types: ^3.4.3
  flutter_chat_ui: ^1.6.2
  flutter_map: ^3.1.0
  flutter_map_location_marker: ^5.1.0+1
  flutter_svg: ^1.1.5
  flutter_vector_icons: ^2.0.0
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  graphql_flutter: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.5.0
  latlong2: ^0.8.1
  lifecycle: ^0.6.0
  map_launcher: ^2.4.0
  meta: ^1.3.0
  modal_bottom_sheet: ^2.1.2
  package_info_plus: ^1.4.3+1
  pinput: ^2.2.16
  shimmer: ^2.0.0
  timeago_flutter: ^1.2.0
  url_launcher: ^6.1.6
  velocity_x: ^3.5.1
  client_shared:
    path: ../../libs/client-shared

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/dotted-lines-1.png
    - images/registration-illustration.png
    - images/logo.png
    - images/marker.png
    - images/marker_pickup.png
    - images/marker_destination.png
    - google_fonts/
